version: '3'
services:
  frontend:
      container_name: "frontend"
      build: ./app/
      restart: always
      environment:
        CHOKIDAR_USEPOLLING: "true"
      ports:
        - '3000:3000'
      command: yarn start
      volumes:
        - ./app:/src
        - /src/node_modules
